cmake_minimum_required(VERSION 3.22)
foreach(required IN ITEMS SOURCE_ROOT BINARY_ROOT SDK_ROOT VCPKG_ROOT ABIS JOBS VARIANT)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
if(NOT VARIANT MATCHES "^(Release|Debug)$" OR NOT JOBS MATCHES "^[1-9][0-9]*$")
  message(FATAL_ERROR "Invalid build variant or jobs")
endif()
find_program(JAVA java HINTS "$ENV{JAVA_HOME}/bin")
if(NOT JAVA)
  message(FATAL_ERROR "Java missing in WSL. Install openjdk-17-jdk before building the APK.")
endif()
execute_process(COMMAND "${JAVA}" -version ERROR_VARIABLE version OUTPUT_VARIABLE stdout RESULT_VARIABLE result)
if(NOT result EQUAL 0 OR NOT "${version}${stdout}" MATCHES "version \"(1[7-9]|[2-9][0-9])")
  message(FATAL_ERROR "Use JDK 17 or newer for Android.")
endif()
set(ndk "${SDK_ROOT}/ndk/29.0.13599879")
foreach(component IN ITEMS "${ndk}/build/cmake/android.toolchain.cmake" "${SDK_ROOT}/cmake/3.22.1/bin/cmake" "${SDK_ROOT}/platforms/android-36/android.jar" "${SDK_ROOT}/build-tools/35.0.0/aapt2" "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
  if(NOT EXISTS "${component}")
    message(FATAL_ERROR "Required Android component missing: ${component}. See COMPILACAO.md.")
  endif()
endforeach()
if(VARIANT STREQUAL "Release")
  set(keystore "$ENV{RELEASE_KEYSTORE}")
  if(keystore STREQUAL "")
    set(keystore "$ENV{HOME}/.android/debug.keystore")
  endif()
  if(NOT EXISTS "${keystore}")
    message(FATAL_ERROR "Set RELEASE_KEYSTORE to the keystore used by the previous APK. See COMPILACAO.md.")
  endif()
endif()
set(env "ANDROID_HOME=${SDK_ROOT}" "ANDROID_SDK_ROOT=${SDK_ROOT}" "ANDROID_NDK_HOME=${ndk}" "VCPKG_ROOT=${VCPKG_ROOT}" "OTCLIENT_ANDROID_ABIS=${ABIS}" "VCPKG_MAX_CONCURRENCY=${JOBS}" "CMAKE_BUILD_PARALLEL_LEVEL=${JOBS}")
string(REPLACE "," ";" abis "${ABIS}")
set(build_luajit FALSE)
foreach(abi IN LISTS abis)
  if(NOT abi MATCHES "^(arm64-v8a|armeabi-v7a|x86_64|x86)$")
    message(FATAL_ERROR "Unsupported ABI: ${abi}")
  endif()
  if(NOT EXISTS "${SOURCE_ROOT}/android/app/libs/lib/${abi}/libluajit-5.1.a")
    set(build_luajit TRUE)
  endif()
endforeach()
if(NOT EXISTS "${SOURCE_ROOT}/android/app/libs/include/luajit/lua.h")
  set(build_luajit TRUE)
endif()
if(build_luajit)
  if(NOT EXISTS "${SOURCE_ROOT}/luajit-src/src/Makefile")
    message(FATAL_ERROR "LuaJIT source is missing in luajit-src.")
  endif()
  find_program(BASH bash REQUIRED)
  file(READ "${SOURCE_ROOT}/build_luajit_android.sh" script)
  string(REPLACE "\r\n" "\n" script "${script}")
  file(WRITE "${BINARY_ROOT}/build-luajit-normalized.sh" "${script}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${env} "${BASH}" -c "source \"$1\"" _ "${BINARY_ROOT}/build-luajit-normalized.sh"
    WORKING_DIRECTORY "${SOURCE_ROOT}" COMMAND_ERROR_IS_FATAL ANY)
endif()
set(asset_zip "${SOURCE_ROOT}/android/app/src/main/assets/data.zip")
file(MAKE_DIRECTORY "${SOURCE_ROOT}/android/app/src/main/assets")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${asset_zip}.new" --format=zip -- data mods modules init.lua otclientrc.lua config.ini cacert.pem
  WORKING_DIRECTORY "${SOURCE_ROOT}" COMMAND_ERROR_IS_FATAL ANY)
file(RENAME "${asset_zip}.new" "${asset_zip}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${env} "${JAVA}" -Xmx512m
  -classpath "${SOURCE_ROOT}/android/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain
  "assemble${VARIANT}" "-Potclient.android.abis=${ABIS}" "--max-workers=${JOBS}"
  WORKING_DIRECTORY "${SOURCE_ROOT}/android" COMMAND_ERROR_IS_FATAL ANY)
string(TOLOWER "${VARIANT}" variant_dir)
set(apk "${SOURCE_ROOT}/android/app/build/outputs/apk/${variant_dir}/Crystal.apk")
if(NOT EXISTS "${apk}")
  message(FATAL_ERROR "Gradle did not generate ${apk}")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${apk}" "${BINARY_ROOT}/Crystal.apk" COMMAND_ERROR_IS_FATAL ANY)
# Only a successfully completed build reaches the publication step. Debug
# refreshes resources and preserves the last successful release packages.
execute_process(COMMAND "${CMAKE_COMMAND}" "-DSOURCE_ROOT:PATH=${SOURCE_ROOT}" "-DOUTPUT_ROOT:PATH=${SOURCE_ROOT}/files"
  -P "${SOURCE_ROOT}/cmake/SyncUpdaterFiles.cmake" COMMAND_ERROR_IS_FATAL ANY)
message(STATUS "Android ${VARIANT} complete; files/ synchronized; APK=${BINARY_ROOT}/Crystal.apk")
