cmake_minimum_required(VERSION 3.25)
if(NOT DEFINED SETTINGS OR NOT EXISTS "${SETTINGS}")
  message(FATAL_ERROR "Run this script through a controller preset.")
endif()
include("${SETTINGS}")

function(run)
  execute_process(COMMAND ${ARGV} COMMAND_ERROR_IS_FATAL ANY)
endfunction()
function(copy_runtime source destination)
  file(MAKE_DIRECTORY "${destination}")
  foreach(directory IN ITEMS data modules mods)
    run("${CMAKE_COMMAND}" -E copy_directory "${source}/${directory}" "${destination}/${directory}")
  endforeach()
  foreach(name IN ITEMS init.lua meta.lua otclientrc.lua config.ini cacert.pem)
    if(EXISTS "${source}/${name}")
      run("${CMAKE_COMMAND}" -E copy_if_different "${source}/${name}" "${destination}/${name}")
    endif()
  endforeach()
endfunction()

if(CRYSTAL_PLATFORM STREQUAL "linux-portable")
  find_program(DOCKER docker REQUIRED)
  run("${DOCKER}" info --format "{{.OSType}}")
  file(READ "${CRYSTAL_SOURCE_DIR}/vcpkg.json" manifest)
  string(JSON baseline GET "${manifest}" builtin-baseline)
  if(NOT baseline MATCHES "^[0-9a-f]+$")
    message(FATAL_ERROR "Invalid vcpkg baseline")
  endif()
  run("${DOCKER}" build --build-arg "VCPKG_REF=${baseline}" -t "${CRYSTAL_DOCKER_IMAGE}" -f "${CRYSTAL_CONTROLLER_DIR}/Dockerfile.linux-portable" "${CRYSTAL_CONTROLLER_DIR}")
  file(MAKE_DIRECTORY "${CRYSTAL_ARTIFACT_DIR}")
  execute_process(COMMAND id -u OUTPUT_VARIABLE uid OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  execute_process(COMMAND id -g OUTPUT_VARIABLE gid OUTPUT_STRIP_TRAILING_WHITESPACE COMMAND_ERROR_IS_FATAL ANY)
  run("${DOCKER}" run --rm
    --mount "type=bind,source=${CRYSTAL_SOURCE_DIR},target=/source,readonly"
    --mount "type=bind,source=${CRYSTAL_CONTROLLER_DIR},target=/controller,readonly"
    --mount "type=bind,source=${CRYSTAL_ARTIFACT_DIR},target=/export"
    --mount "type=volume,source=${CRYSTAL_DOCKER_VOLUME},target=/workspace"
    -e "CRYSTAL_JOBS=${CRYSTAL_JOBS}" -e "CRYSTAL_BUILD_TYPE=${CRYSTAL_BUILD_VARIANT}" -e "EXPORT_UID=${uid}" -e "EXPORT_GID=${gid}"
    "${CRYSTAL_DOCKER_IMAGE}" bash /controller/build-portable.sh)
  return()
endif()

if(NOT EXISTS "${CRYSTAL_VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
  message(FATAL_ERROR "vcpkg missing: ${CRYSTAL_VCPKG_ROOT}. Configure CRYSTAL_VCPKG_ROOT.")
endif()
set(build_env "VCPKG_ROOT=${CRYSTAL_VCPKG_ROOT}" "VCPKG_MAX_CONCURRENCY=${CRYSTAL_JOBS}" "CMAKE_BUILD_PARALLEL_LEVEL=${CRYSTAL_JOBS}")
if(CRYSTAL_PLATFORM STREQUAL "android")
  find_program(JAVA java HINTS "$ENV{JAVA_HOME}/bin" REQUIRED)
  execute_process(COMMAND "${JAVA}" -version ERROR_VARIABLE java_version OUTPUT_VARIABLE java_output)
  if(NOT "${java_version}${java_output}" MATCHES "version \"(1[7-9]|[2-9][0-9])")
    message(FATAL_ERROR "JDK 17 or newer is required; choose JDK 17 for this project.")
  endif()
  set(ndk "${CRYSTAL_ANDROID_SDK}/ndk/${CRYSTAL_ANDROID_NDK_VERSION}")
  foreach(required IN ITEMS "${ndk}/build/cmake/android.toolchain.cmake" "${CRYSTAL_ANDROID_SDK}/platforms/android-36/android.jar" "${CRYSTAL_ANDROID_SDK}/cmake/3.22.1/bin/cmake" "${CRYSTAL_ANDROID_SDK}/build-tools/35.0.0/aapt2")
    if(NOT EXISTS "${required}")
      message(FATAL_ERROR "Android SDK component missing: ${required}. Follow LEIA-ME.md.")
    endif()
  endforeach()
  if(NOT "$ENV{RELEASE_KEYSTORE}" STREQUAL "")
    set(keystore "$ENV{RELEASE_KEYSTORE}")
  else()
    set(keystore "$ENV{HOME}/.android/debug.keystore")
  endif()
  if(NOT EXISTS "${keystore}")
    message(FATAL_ERROR "Signing keystore not found. Set RELEASE_KEYSTORE to the same keystore used by the installed APK; see LEIA-ME.md.")
  endif()
  string(REPLACE "," ";" abis "${CRYSTAL_ANDROID_ABIS}")
  set(needs_luajit FALSE)
  foreach(abi IN LISTS abis)
    if(NOT abi MATCHES "^(arm64-v8a|armeabi-v7a|x86_64|x86)$")
      message(FATAL_ERROR "Unsupported ABI: ${abi}")
    endif()
    if(NOT EXISTS "${CRYSTAL_SOURCE_DIR}/android/app/libs/lib/${abi}/libluajit-5.1.a")
      set(needs_luajit TRUE)
    endif()
  endforeach()
  if(NOT EXISTS "${CRYSTAL_SOURCE_DIR}/android/app/libs/include/luajit/lua.h")
    set(needs_luajit TRUE)
  endif()
  list(APPEND build_env "ANDROID_HOME=${CRYSTAL_ANDROID_SDK}" "ANDROID_SDK_ROOT=${CRYSTAL_ANDROID_SDK}" "ANDROID_NDK_HOME=${ndk}" "OTCLIENT_ANDROID_ABIS=${CRYSTAL_ANDROID_ABIS}")
  if(needs_luajit)
    if(NOT EXISTS "${CRYSTAL_SOURCE_DIR}/luajit-src/src/Makefile")
      message(FATAL_ERROR "LuaJIT source missing: prepare luajit-src as described in LEIA-ME.md.")
    endif()
    find_program(BASH bash REQUIRED)
    file(READ "${CRYSTAL_SOURCE_DIR}/build_luajit_android.sh" luajit_script)
    string(REPLACE "\r\n" "\n" luajit_script "${luajit_script}")
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/build-luajit-normalized.sh" "${luajit_script}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${build_env} "${BASH}" -c "source \"$1\"" _ "${CMAKE_CURRENT_BINARY_DIR}/build-luajit-normalized.sh"
      WORKING_DIRECTORY "${CRYSTAL_SOURCE_DIR}" COMMAND_ERROR_IS_FATAL ANY)
  endif()
  file(MAKE_DIRECTORY "${CRYSTAL_SOURCE_DIR}/android/app/src/main/assets")
  set(asset_zip "${CRYSTAL_SOURCE_DIR}/android/app/src/main/assets/data.zip")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${asset_zip}.new" --format=zip -- data mods modules init.lua otclientrc.lua config.ini cacert.pem
    WORKING_DIRECTORY "${CRYSTAL_SOURCE_DIR}" COMMAND_ERROR_IS_FATAL ANY)
  file(RENAME "${asset_zip}.new" "${asset_zip}")
  # Invoke the checked-in Gradle Wrapper JAR directly, avoiding Windows CRLF and chmod problems.
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${build_env} "${JAVA}" -Xmx512m -classpath "${CRYSTAL_SOURCE_DIR}/android/gradle/wrapper/gradle-wrapper.jar"
    org.gradle.wrapper.GradleWrapperMain assembleRelease "-Potclient.android.abis=${CRYSTAL_ANDROID_ABIS}" "--max-workers=${CRYSTAL_JOBS}"
    WORKING_DIRECTORY "${CRYSTAL_SOURCE_DIR}/android" COMMAND_ERROR_IS_FATAL ANY)
  file(MAKE_DIRECTORY "${CRYSTAL_ARTIFACT_DIR}/updater")
  foreach(name IN ITEMS Crystal.apk android-version.json)
    run("${CMAKE_COMMAND}" -E copy_if_different "${CRYSTAL_SOURCE_DIR}/android-output/updater/${name}" "${CRYSTAL_ARTIFACT_DIR}/updater/${name}")
  endforeach()
else()
  set(extra "-DCMAKE_BUILD_TYPE=Release" "-DOPTIONS_ENABLE_IPO=OFF" "-DSPEED_UP_BUILD_UNITY=OFF")
  if(CRYSTAL_PLATFORM STREQUAL "windows")
    set(preset windows-x64-release)
    list(APPEND extra "-DVCPKG_PLATFORM_TOOLSET=${CRYSTAL_WINDOWS_TOOLSET}")
    set(binary "${CRYSTAL_SOURCE_DIR}/dist/${preset}/Clientex64.exe")
  else()
    set(preset linux-x64-release)
    foreach(compiler IN ITEMS "${CRYSTAL_LINUX_CC}" "${CRYSTAL_LINUX_CXX}")
      if(NOT EXISTS "${compiler}")
        message(FATAL_ERROR "Compiler not found: ${compiler}")
      endif()
    endforeach()
    list(APPEND extra "-DCMAKE_C_COMPILER=${CRYSTAL_LINUX_CC}" "-DCMAKE_CXX_COMPILER=${CRYSTAL_LINUX_CXX}" "-DTOGGLE_DIRECTX=OFF")
    set(binary "${CRYSTAL_SOURCE_DIR}/dist/${preset}/Crystal")
  endif()
  run("${CMAKE_COMMAND}" -E env ${build_env} "${CMAKE_COMMAND}" --preset "${preset}" -S "${CRYSTAL_SOURCE_DIR}" -B "${CRYSTAL_NATIVE_BUILD_DIR}"
    "-DCMAKE_TOOLCHAIN_FILE=${CRYSTAL_VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" "-DVCPKG_INSTALLED_DIR=${CRYSTAL_NATIVE_BUILD_DIR}/vcpkg_installed" ${extra})
  run("${CMAKE_COMMAND}" -E env ${build_env} "${CMAKE_COMMAND}" --build "${CRYSTAL_NATIVE_BUILD_DIR}" --parallel "${CRYSTAL_JOBS}")
  file(MAKE_DIRECTORY "${CRYSTAL_ARTIFACT_DIR}/client" "${CRYSTAL_ARTIFACT_DIR}/updater")
  copy_runtime("${CRYSTAL_SOURCE_DIR}" "${CRYSTAL_ARTIFACT_DIR}/client")
  run("${CMAKE_COMMAND}" -E copy_if_different "${binary}" "${CRYSTAL_ARTIFACT_DIR}/client")
  run("${CMAKE_COMMAND}" -E copy_if_different "${binary}" "${CRYSTAL_ARTIFACT_DIR}/updater")
endif()

message(STATUS "Completed: ${CRYSTAL_ARTIFACT_DIR}")
