FROM ubuntu:22.04
ARG DEBIAN_FRONTEND=noninteractive
ARG VCPKG_REF
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates software-properties-common curl git build-essential \
    autoconf autoconf-archive automake libtool libtool-bin pkg-config \
    ninja-build python3 python3-pip zip unzip tar rsync nasm bison flex \
    libx11-dev libxrandr-dev libxi-dev libxcursor-dev libxinerama-dev \
    libgl1-mesa-dev libglu1-mesa-dev libpulse-dev libltdl-dev \
    && add-apt-repository -y ppa:ubuntu-toolchain-r/test \
    && apt-get update && apt-get install -y --no-install-recommends gcc-13 g++-13 \
    && pip3 install --no-cache-dir cmake==3.31.8 \
    && rm -rf /var/lib/apt/lists/*
RUN test -n "$VCPKG_REF" && git clone https://github.com/microsoft/vcpkg.git /opt/vcpkg \
    && git -C /opt/vcpkg checkout "$VCPKG_REF" && /opt/vcpkg/bootstrap-vcpkg.sh -disableMetrics
ENV VCPKG_ROOT=/opt/vcpkg
ENV CC=/usr/bin/gcc-13
ENV CXX=/usr/bin/g++-13
WORKDIR /workspace
