if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "Use Ubuntu WSL for portable Linux presets.")
endif()
set(CRYSTAL_PLATFORM "linux-portable")
set(CRYSTAL_SOURCE_DIR "${CMAKE_SOURCE_DIR}")
set(CRYSTAL_JOBS "10" CACHE STRING "Portable build parallel limit")
set(CRYSTAL_ARTIFACT_DIR "${CMAKE_BINARY_DIR}/portable-export")
if(NOT DEFINED CRYSTAL_DISTRIBUTION_PRESET)
  get_filename_component(CRYSTAL_DISTRIBUTION_PRESET "${CMAKE_BINARY_DIR}" NAME)
endif()
set(CRYSTAL_DOCKER_IMAGE "crystal-linux-jammy-gcc13")
set(CRYSTAL_DOCKER_VOLUME "crystal-linux-jammy-${CMAKE_BUILD_TYPE}-work")
set(CRYSTAL_CONTROLLER_DIR "${CMAKE_SOURCE_DIR}")
file(WRITE "${CMAKE_BINARY_DIR}/portable-settings.cmake"
  "set(CRYSTAL_PLATFORM linux-portable)\nset(CRYSTAL_SOURCE_DIR [==[${CRYSTAL_SOURCE_DIR}]==])\nset(CRYSTAL_JOBS ${CRYSTAL_JOBS})\nset(CRYSTAL_ARTIFACT_DIR [==[${CRYSTAL_ARTIFACT_DIR}]==])\nset(CRYSTAL_DOCKER_IMAGE ${CRYSTAL_DOCKER_IMAGE})\nset(CRYSTAL_DOCKER_VOLUME ${CRYSTAL_DOCKER_VOLUME})\nset(CRYSTAL_CONTROLLER_DIR [==[${CRYSTAL_CONTROLLER_DIR}]==])\nset(CRYSTAL_BUILD_VARIANT ${CMAKE_BUILD_TYPE})\n")
add_custom_target(portable ALL COMMAND "${CMAKE_COMMAND}"
  "-DSETTINGS:FILEPATH=${CMAKE_BINARY_DIR}/portable-settings.cmake" -P "${CMAKE_SOURCE_DIR}/Build.cmake"
  COMMAND "${CMAKE_COMMAND}" -E make_directory "${CMAKE_BINARY_DIR}/bin"
  COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CRYSTAL_ARTIFACT_DIR}/client/Crystal" "${CMAKE_BINARY_DIR}/bin/Crystal"
  COMMAND "${CMAKE_COMMAND}" "-DSOURCE_ROOT:PATH=${CMAKE_SOURCE_DIR}"
    "-DBINARY_ROOT:PATH=${CMAKE_BINARY_DIR}" "-DBINARY_FILE:FILEPATH=${CMAKE_BINARY_DIR}/bin/Crystal"
    "-DBUILD_CONFIG=${CMAKE_BUILD_TYPE}" "-DPRESET=${CRYSTAL_DISTRIBUTION_PRESET}"
    -P "${CMAKE_SOURCE_DIR}/dist/scripts/linux-x64-release/StageDistribution.cmake"
  COMMAND "${CMAKE_COMMAND}" "-DSOURCE_ROOT:PATH=${CMAKE_SOURCE_DIR}" "-DOUTPUT_ROOT:PATH=${CMAKE_SOURCE_DIR}/files"
    "-DBINARY_FILE:FILEPATH=${CMAKE_BINARY_DIR}/bin/Crystal" "-DBINARY_PLATFORM=linux" "-DBINARY_ARCH=x64" "-DBUILD_CONFIG=${CMAKE_BUILD_TYPE}"
    -P "${CMAKE_SOURCE_DIR}/cmake/SyncUpdaterFiles.cmake"
  USES_TERMINAL VERBATIM)
