# Detect the compiler target, including multilib x86 builds on an x64 host.
if(NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64|AMD64|i[3-6]86|x86)$")
  message(FATAL_ERROR "Linux desktop presets require an x86 or x64 compiler target.")
endif()
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
  set(CRYSTAL_LINUX_ARCH x86)
elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
  set(CRYSTAL_LINUX_ARCH x64)
else()
  message(FATAL_ERROR "Unsupported Linux pointer size: ${CMAKE_SIZEOF_VOID_P}")
endif()
if(DEFINED CRYSTAL_LINUX_TARGET_ARCH AND
   NOT CRYSTAL_LINUX_TARGET_ARCH STREQUAL CRYSTAL_LINUX_ARCH)
  message(FATAL_ERROR "Preset requires ${CRYSTAL_LINUX_TARGET_ARCH}, but compiler targets ${CRYSTAL_LINUX_ARCH}. Install the matching multilib compiler and use a separate build directory.")
endif()
if(DEFINED VCPKG_TARGET_TRIPLET AND NOT VCPKG_TARGET_TRIPLET STREQUAL "${CRYSTAL_LINUX_ARCH}-linux")
  message(FATAL_ERROR "Linux ${CRYSTAL_LINUX_ARCH} requires the ${CRYSTAL_LINUX_ARCH}-linux vcpkg triplet.")
endif()
if(NOT DEFINED CRYSTAL_DISTRIBUTION_PRESET)
  get_filename_component(CRYSTAL_DISTRIBUTION_PRESET "${CMAKE_BINARY_DIR}" NAME)
endif()
if(NOT CRYSTAL_DISTRIBUTION_PRESET MATCHES "^[A-Za-z0-9_-]+$")
  message(FATAL_ERROR "Invalid Linux distribution preset")
endif()
