# Build a small first-run package without changing the full distribution or updater.
cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()
get_filename_component(SOURCE_ROOT "${SOURCE_ROOT}" ABSOLUTE)
if(NOT DEFINED PLATFORM)
  set(PLATFORM windows)
endif()
if(PLATFORM STREQUAL "linux")
  if(NOT DEFINED BINARY_FILE)
    set(BINARY_FILE "${SOURCE_ROOT}/dist/dist-linux/Crystal")
  endif()
elseif(PLATFORM STREQUAL "windows")
  if(NOT DEFINED BINARY_ARCH)
    set(BINARY_ARCH x64)
  endif()
  if(NOT BINARY_ARCH MATCHES "^(x86|x64)$")
    message(FATAL_ERROR "Unsupported Windows architecture: ${BINARY_ARCH}")
  endif()
  if(NOT DEFINED BINARY_FILE)
    set(BINARY_FILE "${SOURCE_ROOT}/dist/dist-windows/Cliente${BINARY_ARCH}.exe")
  endif()
else()
  message(FATAL_ERROR "Unsupported platform: ${PLATFORM}")
endif()
get_filename_component(DISTRIBUTION_ROOT "${BINARY_FILE}" DIRECTORY)
if(NOT DEFINED OUTPUT_ROOT)
  if(PLATFORM STREQUAL "windows" AND BINARY_ARCH STREQUAL "x86")
    set(OUTPUT_ROOT "${SOURCE_ROOT}/build/installer/windows-x86/CrystalClient")
  else()
    set(OUTPUT_ROOT "${SOURCE_ROOT}/build/installer/CrystalClient")
  endif()
endif()
get_filename_component(OUTPUT_ROOT "${OUTPUT_ROOT}" ABSOLUTE)
get_filename_component(OUTPUT_NAME "${OUTPUT_ROOT}" NAME)
if(NOT OUTPUT_NAME STREQUAL "CrystalClient")
  message(FATAL_ERROR "The staging directory must be named CrystalClient")
endif()

# These modules are loaded by init.lua or required by updater.otmod/background.otmod.
set(BOOTSTRAP_MODULES
    corelib gamelib modulelib startup game_shaders
    client_locales client_styles client_background client_topmenu updater)
foreach(REQUIRED_FILE IN ITEMS
    init.lua cacert.pem config.ini data/setup.otml)
  if(NOT EXISTS "${SOURCE_ROOT}/${REQUIRED_FILE}")
    message(FATAL_ERROR "Required installer source is missing: ${REQUIRED_FILE}")
  endif()
endforeach()
foreach(MODULE IN LISTS BOOTSTRAP_MODULES)
  if(NOT IS_DIRECTORY "${SOURCE_ROOT}/modules/${MODULE}")
    message(FATAL_ERROR "Required updater module is missing: ${MODULE}")
  endif()
endforeach()
foreach(DIRECTORY IN ITEMS cursors fonts images locales particles styles)
  if(NOT IS_DIRECTORY "${SOURCE_ROOT}/data/${DIRECTORY}")
    message(FATAL_ERROR "Required updater resource is missing: data/${DIRECTORY}")
  endif()
endforeach()

# This installer targets the static Release build, rather than the former DLL package.
if(NOT EXISTS "${BINARY_FILE}")
  message(FATAL_ERROR "Client executable is missing: ${BINARY_FILE}")
endif()
if(PLATFORM STREQUAL "windows")
file(GLOB DYNAMIC_LIBRARIES "${DISTRIBUTION_ROOT}/*.dll" "${DISTRIBUTION_ROOT}/*.DLL")
if(DYNAMIC_LIBRARIES AND NOT ALLOW_DYNAMIC_LIBRARIES)
  message(FATAL_ERROR "${DISTRIBUTION_ROOT} contains DLLs. Build the matching static Windows preset into a clean distribution before creating this installer.")
endif()
endif()
file(READ "${SOURCE_ROOT}/init.lua" BOOTSTRAP_INIT)
if(NOT BOOTSTRAP_INIT MATCHES "updater[ \t]*=[ \t]*\"https://[^\"]+\"")
  message(FATAL_ERROR "init.lua must configure an HTTPS updater for the first-run package")
endif()
if(NOT BOOTSTRAP_INIT MATCHES "local function loadModules\\(\\)")
  message(FATAL_ERROR "init.lua startup changed; review the bootstrap callback before packaging")
endif()

# A cancelled/failed first download must not try to open missing game modules.
# Only the packaged init.lua is adjusted. The updater replaces it with the complete
# server version and restarts once the missing .otmod files have been downloaded.
string(REPLACE "local function loadModules()" [=[local function loadModules()
    if not g_modules.getModule('client') or not g_modules.getModule('game_interface') or
       not g_modules.getModule('client_mods') then
        g_logger.info('Initial download incomplete. Open Crystal again to retry the updater.')
        g_app.exit()
        return
    end]=] BOOTSTRAP_INIT "${BOOTSTRAP_INIT}")

# Never remove an existing folder unless this script created it as temporary staging.
set(STAGING_MARKER "${OUTPUT_ROOT}/.crystal-installer-stage")
if(EXISTS "${OUTPUT_ROOT}")
  if(NOT EXISTS "${STAGING_MARKER}")
    message(FATAL_ERROR "Refusing to replace an unmarked staging directory: ${OUTPUT_ROOT}")
  endif()
  file(REMOVE_RECURSE "${OUTPUT_ROOT}")
endif()
file(MAKE_DIRECTORY "${OUTPUT_ROOT}/data" "${OUTPUT_ROOT}/modules")
file(WRITE "${STAGING_MARKER}" "Temporary installer staging; recreated by StageWindowsInstaller.cmake.\n")
file(COPY "${BINARY_FILE}" "${SOURCE_ROOT}/cacert.pem"
          "${SOURCE_ROOT}/config.ini" DESTINATION "${OUTPUT_ROOT}")
if(PLATFORM STREQUAL "windows" AND ALLOW_DYNAMIC_LIBRARIES AND DYNAMIC_LIBRARIES)
  file(COPY ${DYNAMIC_LIBRARIES} DESTINATION "${OUTPUT_ROOT}")
endif()
file(WRITE "${OUTPUT_ROOT}/init.lua" "${BOOTSTRAP_INIT}")
if(EXISTS "${SOURCE_ROOT}/LICENSE")
  file(COPY "${SOURCE_ROOT}/LICENSE" DESTINATION "${OUTPUT_ROOT}")
endif()
file(COPY "${SOURCE_ROOT}/data/setup.otml" DESTINATION "${OUTPUT_ROOT}/data")
foreach(DIRECTORY IN ITEMS cursors fonts locales particles styles)
  file(COPY "${SOURCE_ROOT}/data/${DIRECTORY}" DESTINATION "${OUTPUT_ROOT}/data")
endforeach()
# Keep the interface art used by styles, startup and the updater background.
# World/game artwork, sprites, sounds and game metadata come from the updater.
file(COPY "${SOURCE_ROOT}/data/images" DESTINATION "${OUTPUT_ROOT}/data"
     PATTERN "game" EXCLUDE)
foreach(MODULE IN LISTS BOOTSTRAP_MODULES)
  file(COPY "${SOURCE_ROOT}/modules/${MODULE}" DESTINATION "${OUTPUT_ROOT}/modules")
endforeach()
message(STATUS "Installer bootstrap package: ${OUTPUT_ROOT}")
message(STATUS "The modules/updater source is preserved; remaining content downloads on first launch.")
