# Post-build desktop distribution: minimal updater seed in dist; full payload in files.
cmake_minimum_required(VERSION 3.24)
foreach(required IN ITEMS SOURCE_ROOT BINARY_FILE PLATFORM BUILD_CONFIG)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "Missing ${required}")
  endif()
endforeach()
get_filename_component(DISTRIBUTION_ROOT "${BINARY_FILE}" DIRECTORY)
if(NOT BUILD_CONFIG MATCHES "^(Release|RelWithDebInfo|MinSizeRel)$")
  # Debug remains a complete developer runtime in build/<preset>/bin.
  foreach(dir IN ITEMS data modules mods)
    file(COPY "${SOURCE_ROOT}/${dir}" DESTINATION "${DISTRIBUTION_ROOT}")
  endforeach()
  foreach(name IN ITEMS init.lua meta.lua config.ini cacert.pem otclientrc.lua)
    file(COPY "${SOURCE_ROOT}/${name}" DESTINATION "${DISTRIBUTION_ROOT}")
  endforeach()
  return()
endif()
set(DISTRIBUTION_KEY "${PLATFORM}")
set(EXPECTED_DISTRIBUTION "${SOURCE_ROOT}/dist/dist-${PLATFORM}")
if(PLATFORM STREQUAL "windows")
  if(NOT DEFINED BINARY_ARCH)
    set(BINARY_ARCH x64)
  endif()
  if(NOT BINARY_ARCH MATCHES "^(x86|x64)$")
    message(FATAL_ERROR "Unsupported Windows architecture: ${BINARY_ARCH}")
  endif()
  set(DISTRIBUTION_KEY "windows-${BINARY_ARCH}")
endif()
cmake_path(NORMAL_PATH EXPECTED_DISTRIBUTION)
cmake_path(NORMAL_PATH DISTRIBUTION_ROOT)
if(NOT DISTRIBUTION_ROOT STREQUAL EXPECTED_DISTRIBUTION)
  message(FATAL_ERROR "Unexpected desktop distribution: ${DISTRIBUTION_ROOT}")
endif()
set(OUTPUT_ROOT "${SOURCE_ROOT}/build/distribution-bootstrap/${DISTRIBUTION_KEY}/CrystalClient")
include("${CMAKE_CURRENT_LIST_DIR}/StageClientBootstrap.cmake")
# Keep prior runtime files/symbols recoverable outside dist, never in download packages.
string(TIMESTAMP stamp "%Y%m%d-%H%M%S")
string(RANDOM LENGTH 8 suffix)
set(backup "${SOURCE_ROOT}/build/distribution-full/${DISTRIBUTION_KEY}-${stamp}-${suffix}")
file(GLOB entries LIST_DIRECTORIES TRUE "${DISTRIBUTION_ROOT}/*")
foreach(entry IN LISTS entries)
  if(NOT entry STREQUAL BINARY_FILE)
    get_filename_component(name "${entry}" NAME)
    # The other Windows target must survive refreshing the shared runtime.
    if(PLATFORM STREQUAL "windows" AND name MATCHES "^Cliente(x86|x64)\\.exe$")
      continue()
    endif()
    file(MAKE_DIRECTORY "${backup}")
    file(RENAME "${entry}" "${backup}/${name}")
  endif()
endforeach()
file(GLOB seed LIST_DIRECTORIES TRUE "${OUTPUT_ROOT}/*")
foreach(entry IN LISTS seed)
  get_filename_component(name "${entry}" NAME)
  if(NOT name STREQUAL ".crystal-installer-stage")
    file(COPY "${entry}" DESTINATION "${DISTRIBUTION_ROOT}")
  endif()
endforeach()
message(STATUS "Minimal first-run distribution: ${DISTRIBUTION_ROOT}")
