include_guard(GLOBAL)
# Web only: do not modify the native presets or the user's shell startup files.
get_filename_component(CRYSTAL_WEB_SOURCE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(CRYSTAL_EMSDK_VERSION "4.0.23")
if(NOT CRYSTAL_EMSDK_ROOT)
  foreach(candidate IN ITEMS "$ENV{EMSDK}" "${CRYSTAL_WEB_SOURCE_ROOT}/.tools/emsdk" "$ENV{HOME}/emsdk")
    if(EXISTS "${candidate}/upstream/emscripten/emcc")
      set(CRYSTAL_EMSDK_ROOT "${candidate}" CACHE PATH "Emscripten SDK root")
      break()
    endif()
  endforeach()
endif()
if(NOT EXISTS "${CRYSTAL_EMSDK_ROOT}/upstream/emscripten/emcc")
  message(FATAL_ERROR "Emscripten ${CRYSTAL_EMSDK_VERSION} missing. Run bash dist/scripts/web-release/preparar-ambiente.sh from the project root.")
endif()
set(ENV{EMSDK} "${CRYSTAL_EMSDK_ROOT}")
# Make-based cross ports preserve an existing CC/CXX. Let vcpkg select
# emcc/em++ for wasm and the system compiler for host tools instead.
unset(ENV{CC})
unset(ENV{CXX})
execute_process(COMMAND "${CRYSTAL_EMSDK_ROOT}/upstream/emscripten/emcc" --version
  RESULT_VARIABLE sdk_result OUTPUT_VARIABLE sdk_version ERROR_VARIABLE sdk_error)
if(NOT sdk_result EQUAL 0 OR NOT sdk_version MATCHES "${CRYSTAL_EMSDK_VERSION}([ \r\n]|$)")
  message(FATAL_ERROR "Activate Emscripten ${CRYSTAL_EMSDK_VERSION}: bash dist/scripts/web-release/preparar-ambiente.sh\n${sdk_version}${sdk_error}")
endif()
if(NOT CRYSTAL_WEB_VCPKG_ROOT)
  foreach(candidate IN ITEMS "$ENV{VCPKG_ROOT}" "$ENV{HOME}/vcpkg" "${CRYSTAL_WEB_SOURCE_ROOT}/.tools/vcpkg" "${CRYSTAL_WEB_SOURCE_ROOT}/../vcpkg")
    if(EXISTS "${candidate}/vcpkg" AND EXISTS "${candidate}/scripts/buildsystems/vcpkg.cmake")
      set(CRYSTAL_WEB_VCPKG_ROOT "${candidate}" CACHE PATH "Host vcpkg used for web dependencies")
      break()
    endif()
  endforeach()
endif()
if(NOT EXISTS "${CRYSTAL_WEB_VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
  message(FATAL_ERROR "Linux vcpkg missing. Run bash dist/scripts/web-release/preparar-ambiente.sh.")
endif()
set(ENV{VCPKG_ROOT} "${CRYSTAL_WEB_VCPKG_ROOT}")
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CRYSTAL_EMSDK_ROOT}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" CACHE FILEPATH "Emscripten chainload toolchain")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CRYSTAL_EMSDK_ROOT CRYSTAL_WEB_VCPKG_ROOT)
